xcodebuild_arguments:
  - -scheme
  - HKDF
module: HKDF
author: Bouke Haarsma
author_url: https://twitter.com/BoukeHaarsma
output: ../HKDF-Docs/master
theme: fullwidth
clean: true
github_url: https://github.com/Bouke/HKDF
dash_url: http://boukehaarsma.nl/HKDF/HKDF.xml
